### ISSUE TITLE
Juicer post & only hi-c contact maps with no scaffolding

### ISSUE THREAD

**Issue by ShadeNiece** [c-zhou/yahs#102]
Hello,

I have an assembly that I scaffolded with yahs, then ran purge_haplotigs, tgs_gapcloser and then re-scaffolded for a second time, which ended up joining a couple of my homologous chromosomes. Also, I have a predicted autotetraploid tree species that I'm working with, so I was initially doing the second round of scaffolding to make sure that I didn't change my scaffolds too much during purge_haplotigs. After manually fixing the scaffolds in JBAT from the second round of scaffolding, I tried to run the juicer post processing script on my new review.assembly file and got the following error. I can't really seem to find any definitive solutions based on any previous issues, so I was hoping to get some help.
```
[I::main_post] writing FASTA file for scaffolds
[E::make_asm_dict_from_agp] invalid sequence component ptg000140l:1-70172665 on scaffold_1
[E::make_asm_dict_from_agp] sequence end position (70172665) greater than sequence length (2839837)
```

Is it necessary to actually scaffold for a second time, or could I just create a new hi-c contact map without actually scaffolding? If so, would I need to use the files from the first round of scaffolding (other than my new fasta)?

Thank you!

**Comment by c-zhou** [comment]
Hi @ShadeNiece,

The `juicer post` command takes three positional parameters: `<review.assembly> <liftover.agp> <contigs.fa>`. Based on the error message, it seems the `<contigs.fa>` input might be incorrect - it should be the same file used for `juicer pre`, which in turn should match the one used for the second round of scaffolding. You mentioned performing purge_haplotigs after the first round of scaffolding, so I guess the inputs are different for the first and second round scaffolding. It might be worth checking if the inputs were correct.

Your pipeline is a bit unclear to me. After running purge_haplotigs and tgs_gapcloser, you generated a new FASTA file. Is this the FASTA file used for the second round of scaffolding? Additionally, did you remap your Hi-C data to this updated FASTA file? If you can clarify these points, I might be able to provide more specific guidance.

Best,
Chenxi

**Comment by ShadeNiece** [comment]
@c-zhou 
Thank you for the response! To clarify, I used the fasta generated from the 1st round of scaffolding as input for purge_haplotigs and tgs_gapscloser. The final fasta produced by tgs_gapcloser was used as input for the 2nd round of scaffolding (juicer pre and juicer post). I did also verify that I was using the corrent contig.fa file for the second round of scaffolding during juicer pre and juicer post. 

And yes, I did remap my Hi-C data to this updated fasta file that was produced after tgs_gapcloser. After scaffolding this new fasta and loading it into JBAT, it fused two of my chromosomes, so that's why I was cuirous if I could just create the hi-c maps without actually scaffolding-just to look at the final assembly after purging haplotigs and closing gaps.

I hope this clarifies, but please let me know if you need any other information!

**Comment by c-zhou** [comment]
Hi @ShadeNiece,

Thank you for the clarification. Let us confirm the steps: after running purge_haplotigs and tgs_gapcloser, you generated a FASTA file named `new_scaf.fa`. You then remapped the Hi-C data to `new_scaf.fa`, resulting in a Hi-C file named `new_hic.bam` (or `new_hic.bed`). Next, you ran:
```
yahs ... -o out new_scaf.fa new_hic.bam
juicer pre ... new_hic.bam out_scaffolds_final.agp new_scaf.fa.fai
juicer post ... review.assembly liftover.agp new_scaf.fa
```

Is that correct? If so, you might want to check that `new_scaf.fa.fai` matches the `new_scaf.fa` file to ensure consistency.

Whether running a second round of scaffolding is worthwhile depends on the extent of improvement it brings to the assembly.

Best,
Chenxi

**Comment by c-zhou** [comment]
```
[I::main_post] writing FASTA file for scaffolds
[E::make_asm_dict_from_agp] invalid sequence component ptg000140l:1-70172665 on scaffold_1
[E::make_asm_dict_from_agp] sequence end position (70172665) greater than sequence length (2839837)
```
This error says, the AGP file (`liftover.agp`) contains a line for the contig `ptg000140l:1-70172665`, which specifies a sequence length of 70172665. However, the actual sequence length in the contig file (`new_scaf.fa`) is 2839837.

Best,
Chenxi

**Comment by ShadeNiece** [comment]
@c-zhou 

I ended up just completely restarting scaffolding, and that seemed to fix it even though I was sure I was using all of the correct files. I'm not sure why, but I just wanted to let you know that the issue resolved itself after I re-ran scaffolding.

Thank you for your help regardless!
