### ISSUE TITLE
not quite understanding the relationship between the hic map and the scaffolding

### ISSUE THREAD

**Issue by AlcaArctica** [c-zhou/yahs#104]
So I am struggeling a bit with the following problem:
I have the following HiC map:
<img width="885" alt="image" src="https://github.com/user-attachments/assets/b9f513ad-a3c9-43e8-9450-ff85f6f06259">

I know it doesnt look too good, but we can put that aside for the moment.

I am interested in the bottom, right corner here:
<img width="885" alt="image" src="https://github.com/user-attachments/assets/3cf59e13-2960-48d3-8bd9-ba30eff773ff">

The last scaffold I have is: `Scaffold name = ctg00005352.1`
<img width="902" alt="image" src="https://github.com/user-attachments/assets/ebfa3723-dfed-4bb3-a3bb-7ac8074ba377">

This one also appears in my `out_JBAT.liftover.agp` file

`ctg00005352.1	1	6000	1	W	h1tg002678l_1	1	6000	+`

But the `out_JBAT.liftover.agp` file continues to:

```
ctg00005714.1	1	1000	1	W	h1tg006908l_1	1	1000	+
ctg00005715.1	1	1000	1	W	h1tg004730l_1	1	1000	+
ctg00005716.1	1	1000	1	W	h1tg008256l_1	1	1000	+
```

**Accordingly my first question 1) So there are **5716** scaffolds in the `out_JBAT.liftover.agp` file, but I can only see **5352** when I look at the HiC map? Can you explain why that is?**

Now, lets say I do the manual curation and save the `hap1.review.assembly` file. (I did not make any changes in this case). Then I run:

```
juicer post -o curated hap1.review.assembly out_JBAT.liftover.agp assembly_haplotig1.fasta
[I::main_post] writing FASTA file for scaffolds
[I::write_fasta_file_from_agp] Number sequences: 2304
[I::write_fasta_file_from_agp] Number bases: 1450780725
[I::main_post] Version: 1.2.2
[I::main_post] CMD: juicer post -o curated hap1.review.assembly out_JBAT.liftover.agp /ptmp/luelze/analysis/fDirArg/scaff/linked_assemblies/assembly_haplotig1.fasta
[I::main_post] Real time: 10.567 sec; CPU: 10.370 sec; Peak RSS: 2.715 GB
```

Now I end up with 2304 scaffolds in the resulting curated assembly fasta file:
```
grep -c ">" curated.FINAL.fa 
2304
```

**Which leads me to my question 2) How do we get from 5716 or 5352 scaffolds down to 2304?** 

I guess I have a major misunderstanding here. I would be very happy if someone could give me a hint! Thank you very much

**Comment by c-zhou** [comment]
Hello @AlcaArctica,

The 5716 sequences listed in the `out_JBAT.liftover.agp` are contigs, not scaffolds. To check the number of scaffolds, you  could check either the final AGP file or FASTA file generated in the `yahs` scaffolding step, which should give you the number 2304.

In the picture you showed above, it seems there are more sequences in the bottom-right corner. Could that be the reason you only saw 5352?

Best,
Chenxi

**Comment by AlcaArctica** [comment]
Thank you @c-zhou . It already seems a bit more clear today. 

So to sum up, I understand that:

1) Green squares are contigs, although in juicebox they are called scaffolds, these come from hifiasm.

2) Blue squares are called superscaffolds when they encompass more than one green square. I am presuming these come from yahs.

<img width="1154" alt="image" src="https://github.com/user-attachments/assets/45a04fdb-7065-48ae-8c06-920192384d2c">

So here in this example we see the superscaffold 6, made up of 5 contigs.

3) When a blue square does not hold two or more green squares it is just a simple scaffold or contig.

<img width="308" alt="image" src="https://github.com/user-attachments/assets/75ebd3fb-10dd-4760-a8a0-8307284ad145">

Here we have several blue squares which are simple contigs or scaffolds.


Both green and blue squares can be manually modified in juicebox.

The aim of the manual curation step is to engineer the blue and green squares in a way (i.e. fixing translocation and inversion errors and so on), so that ideally we generate superscaffolds which correspond to chromosomes. 

Then when the resulting assembly.review file is used to generate a final fasta file, we have a chromosome-resolved assembly. 

So the number of scaffolds in my final curated assembly corresponds to the number of superscaffolds.

Is that correct?

**Comment by c-zhou** [comment]
Hi @AlcaArctica, that is absolutely correct! Chenxi

**Comment by AlcaArctica** [comment]
Great, thanks for humouring me!
