### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by claumer** [c-zhou/yahs#12]
Hello Chenxi,

Having some very nice results with yahs so far, thank you for writing such a nice & comparatively simple-to-use tool. 

However I am finding that one particular dataset I am working with is causing a segmentation fault:

(base) cl16@node-13-27:/lustre/scratch123/tol/teams/blaxter/users/cl16/Drosophila/HiC_scaffolding$ ../../yahs/yahs -o idDroSubo2_yahs idDroSubo2_hifiasm.p_ctg.filtered.fa idDroSubo2_HiC.bam
[I::main] dump hic links to binary file idDroSubo2_yahs.bin
[I::dump_links_from_bam_file] 1 million read pairs processed
[I::dump_links_from_bam_file] 2 million read pairs processed
[I::dump_links_from_bam_file] 3 million read pairs processed
[I::dump_links_from_bam_file] 4 million read pairs processed
[I::dump_links_from_bam_file] 5 million read pairs processed
[I::dump_links_from_bam_file] 6 million read pairs processed
[I::dump_links_from_bam_file] 7 million read pairs processed
Segmentation fault (core dumped)

This is a dataset with 73.7M reads, mapped to the genome with bwa-mem2 -5SP and deduplicated with samblaster. I have run into the same error when running interactively with 40 GB and 100 GB RAM, so I don't think it's a memory limit problem. This is one of a set of 6 Drosophila genomes that I've been scaffolding with yahs, and all of the other 5 have worked beautifully so far with the same pipeline. The input assembly is pretty decent, 338 contigs with N50 1.3 Mb.

I guess it is a bug? I'd very much appreciate any help you can give. You may access the data on the sanger farm if you wish, path is as given in the excerpt above.

Regards,
Chris L

**Comment by c-zhou** [comment]
Hello Chris,

Yes, there was a bug in processing BAM file in the version you are using but should be already fixed in the latest code. Could you do a git pull and rebuild?

Best,
Chenxi

**Comment by claumer** [comment]
Hello Chenxi,

Thanks for this, indeed I was using a version downloaded last year I think. I'll check back in after testing the new build.

One question: does this bam parsing bug mean I should also repeat scaffolding on the other libraries I've successfully used this version of yahs with? Or do you think those scaffoldings are trustworthy so long as the bam parser got through all the reads without a segfault?

Regards,
Chris

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by c-zhou** [comment]
Hi Chris,

That bug was triggered by some rare cases related to processing secondary or supplementary BAM records. These alignment records were not used in scaffolding anyway so should not affect scaffolding results.

Best,
Chenxi

**Comment by claumer** [comment]
Hi Chenxi,

Just writing to follow up - using v1.1a indeed solved the issue and I have lovely scaffolds from this assembly now. I wish all bioinformatics issues were this easy.

One final request to close out the query: is it possible to push a binary release of the v1.1a software? I actually wasn't able to build it myself (got stuck up on the zlib-dev requirement, which is a tricky thing to build without root), but managed to use someone else's binary on the farm. But maybe for users who don't have that option this could be quite valuable?

Thanks again for your help.

Regards,
Chris L

**Comment by fka21** [comment]
Dear Chenxi,

I have encountered a highly similar error when using on a different dataset with v1.2a.1.

```
[I::dump_links_from_bam_file] 431 million records processed, 149827562 read pairs 
[I::dump_links_from_bam_file] 432 million records processed, 150161791 read pairs 
[I::dump_links_from_bam_file] 433 million records processed, 150497311 read pairs 
[I::dump_links_from_bam_file] 434 million records processed, 150834549 read pairs 
[I::dump_links_from_bam_file] 435 million records processed, 151173156 read pairs 
[I::dump_links_from_bam_file] 436 million records processed, 151511550 read pairs 
[I::dump_links_from_bam_file] 437 million records processed, 151850353 read pairs 
[I::dump_links_from_bam_file] 438 million records processed, 152191613 read pairs 
[I::dump_links_from_bam_file] 439 million records processed, 152533097 read pairs 
[I::dump_links_from_bam_file] 440 million records processed, 152875697 read pairs 
[I::dump_links_from_bam_file] 441 million records processed, 153219936 read pairs 
[I::dump_links_from_bam_file] 442 million records processed, 153566403 read pairs 
[I::dump_links_from_bam_file] 443 million records processed, 153913434 read pairs 
[I::dump_links_from_bam_file] 444 million records processed, 154261136 read pairs 
[I::dump_links_from_bam_file] 445 million records processed, 154609680 read pairs 
[I::dump_links_from_bam_file] dumped 154924674 read pairs from 445908994 records: 154924674 intra links + 0 inter links 
[I::run_yahs] RAM total: 995.577GB
[I::run_yahs] RAM limit: 10.814GB
Segmentation fault
```
I am using a similar approach as the person opening this issue, meaning alignment
`bwa-mem2 mem -5 -S -P -t {threads} {input.assembly} {input.reads1} | samtools sort -@ {threads} -n -O bam -o {output.bam1}`
`bwa-mem2 mem -5 -S -P -t {threads} {input.assembly} {input.reads2} | samtools sort -@ {threads} -n -O bam -o {output.bam2}`

And to merge
`bellerophon --forward {input.bam1} --reverse {input.bam2} --quality 20 --output {output.merged_bam} --threads {threads}`

And finally to sort and mark duplicates
`java -jar $CONDA_PREFIX/share/picard-2.20.4-1/picard.jar SortSam I={input} O=01_alignments/temp_sorted.bam SORT_ORDER=queryname`
`java -jar $CONDA_PREFIX/share/picard-2.20.4-1/picard.jar MarkDuplicates I=01_alignments/temp_sorted.bam O={output.marked_bam} M={output.metrics} > {log} 2>&1`

I am using the following command for scaffolding
 `yahs {input.assembly} {input.marked_bam} {params.restriction_site} -o {params.prefix}`
`agp_to_fasta 02_scaffolding/{wildcards.sample}_scaffolds_final.agp {input.assembly} > {output.scaffold}`

Any ideas what could have gotten wrong? I would appreciate any advice!

Cheers,
Ferenc
