### ISSUE TITLE
The option --threads of juicer_tools.jar pre really work?

### ISSUE THREAD

**Issue by xiekunwhy** [c-zhou/yahs#15]
Hi,

I found that you use --threads option in juicer_tools.jar pre command line, but when I use this option, it aways telling me that there is no mndindex file and use single process only.

Best,
Kun

**Comment by c-zhou** [comment]
Hi Kun,

Although not much improvement in the speed (I mentioned in the script `v1.9.9 seems much faster than v1.22.01`), --threads option did work at my end. Please do remember to check the version - this option was introduced recently.

I might not be the right person to answer this question. You check with the juicer team.

Best,
Chenxi
