### ISSUE TITLE
assembly N50 (298818) too small

### ISSUE THREAD

**Issue by aureliendejode** [c-zhou/yahs#16]
Hello,

I used the Arima pipeline to map hi-C reads on my assembly and then ran yahs with the simple command line:
yahs contigs.fa hic-to-contigs.bam

I got the pasted below out message telling me that the N50 is too small.
Is there some tuning or option I can use to make this work ?
Or is that I won't get any result unless I use a more contiguous assembly ?

Thanks for your help

[I::main] dump hic links (BAM) to binary file yahs.out.bin
[I::dump_links_from_bam_file] 1 million records processed, 51351 read pairs 
[I::dump_links_from_bam_file] 2 million records processed, 102273 read pairs 
[I::dump_links_from_bam_file] 3 million records processed, 153904 read pairs 
[I::dump_links_from_bam_file] 4 million records processed, 205760 read pairs 
[I::dump_links_from_bam_file] 5 million records processed, 258805 read pairs 
[I::dump_links_from_bam_file] 6 million records processed, 309007 read pairs 
[I::dump_links_from_bam_file] 7 million records processed, 360969 read pairs 
[I::dump_links_from_bam_file] 8 million records processed, 412212 read pairs 
[I::dump_links_from_bam_file] 9 million records processed, 465283 read pairs 
[I::dump_links_from_bam_file] 10 million records processed, 515586 read pairs 
[I::dump_links_from_bam_file] 11 million records processed, 566344 read pairs 
[I::dump_links_from_bam_file] 12 million records processed, 617132 read pairs 
[I::dump_links_from_bam_file] 13 million records processed, 667682 read pairs 
[I::dump_links_from_bam_file] 14 million records processed, 720137 read pairs 
[I::dump_links_from_bam_file] 15 million records processed, 772370 read pairs 
[I::dump_links_from_bam_file] 16 million records processed, 823607 read pairs 
[I::dump_links_from_bam_file] 17 million records processed, 875877 read pairs 
[I::dump_links_from_bam_file] 18 million records processed, 927975 read pairs 
[I::dump_links_from_bam_file] 19 million records processed, 979503 read pairs 
[I::dump_links_from_bam_file] 20 million records processed, 1030720 read pairs 
[I::dump_links_from_bam_file] 21 million records processed, 1082602 read pairs 
[I::dump_links_from_bam_file] 22 million records processed, 1133204 read pairs 
[I::dump_links_from_bam_file] 23 million records processed, 1184579 read pairs 
[I::dump_links_from_bam_file] 24 million records processed, 1236809 read pairs 
[I::dump_links_from_bam_file] 25 million records processed, 1287042 read pairs 
[I::dump_links_from_bam_file] 26 million records processed, 1338447 read pairs 
[I::dump_links_from_bam_file] 27 million records processed, 1390868 read pairs 
[I::dump_links_from_bam_file] 28 million records processed, 1441553 read pairs 
[I::dump_links_from_bam_file] 29 million records processed, 1493057 read pairs 
[I::dump_links_from_bam_file] 30 million records processed, 1543037 read pairs 
[I::dump_links_from_bam_file] 31 million records processed, 1593968 read pairs 
[I::dump_links_from_bam_file] 32 million records processed, 1645572 read pairs 
[I::dump_links_from_bam_file] 33 million records processed, 1697068 read pairs 
[I::dump_links_from_bam_file] 34 million records processed, 1748400 read pairs 
[I::dump_links_from_bam_file] 35 million records processed, 1800450 read pairs 
[I::dump_links_from_bam_file] 36 million records processed, 1851935 read pairs 
[I::dump_links_from_bam_file] 37 million records processed, 1903602 read pairs 
[I::dump_links_from_bam_file] 38 million records processed, 1956116 read pairs 
[I::dump_links_from_bam_file] 39 million records processed, 2008226 read pairs 
[I::dump_links_from_bam_file] 40 million records processed, 2060902 read pairs 
[I::dump_links_from_bam_file] 41 million records processed, 2112795 read pairs 
[I::dump_links_from_bam_file] 42 million records processed, 2165241 read pairs 
[I::dump_links_from_bam_file] 43 million records processed, 2217975 read pairs 
[I::dump_links_from_bam_file] 44 million records processed, 2269849 read pairs 
[I::dump_links_from_bam_file] 45 million records processed, 2321902 read pairs 
[I::dump_links_from_bam_file] 46 million records processed, 2372714 read pairs 
[I::dump_links_from_bam_file] 47 million records processed, 2424623 read pairs 
[I::dump_links_from_bam_file] 48 million records processed, 2476150 read pairs 
[I::dump_links_from_bam_file] 49 million records processed, 2528241 read pairs 
[I::dump_links_from_bam_file] 50 million records processed, 2580774 read pairs 
[I::dump_links_from_bam_file] 51 million records processed, 2634551 read pairs 
[I::dump_links_from_bam_file] 52 million records processed, 2686771 read pairs 
[I::dump_links_from_bam_file] 53 million records processed, 2739225 read pairs 
[I::dump_links_from_bam_file] 54 million records processed, 2791203 read pairs 
[I::dump_links_from_bam_file] 55 million records processed, 2841962 read pairs 
[I::dump_links_from_bam_file] 56 million records processed, 2894674 read pairs 
[I::dump_links_from_bam_file] 57 million records processed, 2946921 read pairs 
[I::dump_links_from_bam_file] 58 million records processed, 2997320 read pairs 
[I::dump_links_from_bam_file] 59 million records processed, 3048911 read pairs 
[I::dump_links_from_bam_file] 60 million records processed, 3100091 read pairs 
[I::dump_links_from_bam_file] 61 million records processed, 3152562 read pairs 
[I::dump_links_from_bam_file] 62 million records processed, 3205186 read pairs 
[I::dump_links_from_bam_file] 63 million records processed, 3258515 read pairs 
[I::dump_links_from_bam_file] 64 million records processed, 3310661 read pairs 
[I::dump_links_from_bam_file] 65 million records processed, 3362076 read pairs 
[I::dump_links_from_bam_file] 66 million records processed, 3414360 read pairs 
[I::dump_links_from_bam_file] 67 million records processed, 3466602 read pairs 
[I::dump_links_from_bam_file] 68 million records processed, 3519372 read pairs 
[I::dump_links_from_bam_file] 69 million records processed, 3572256 read pairs 
[I::dump_links_from_bam_file] 70 million records processed, 3622672 read pairs 
[I::dump_links_from_bam_file] 71 million records processed, 3675465 read pairs 
[I::dump_links_from_bam_file] 72 million records processed, 3728802 read pairs 
[I::dump_links_from_bam_file] 73 million records processed, 3781337 read pairs 
[I::dump_links_from_bam_file] 74 million records processed, 3834064 read pairs 
[I::dump_links_from_bam_file] 75 million records processed, 3885874 read pairs 
[I::dump_links_from_bam_file] 76 million records processed, 3938304 read pairs 
[I::dump_links_from_bam_file] 77 million records processed, 3989945 read pairs 
[I::dump_links_from_bam_file] 78 million records processed, 4033090 read pairs 
[I::dump_links_from_bam_file] 79 million records processed, 4078689 read pairs 
[I::dump_links_from_bam_file] 80 million records processed, 4129528 read pairs 
[I::dump_links_from_bam_file] 81 million records processed, 4179856 read pairs 
[I::dump_links_from_bam_file] 82 million records processed, 4231979 read pairs 
[I::dump_links_from_bam_file] 83 million records processed, 4283392 read pairs 
[I::dump_links_from_bam_file] 84 million records processed, 4335131 read pairs 
[I::dump_links_from_bam_file] 85 million records processed, 4387735 read pairs 
[I::dump_links_from_bam_file] 86 million records processed, 4440247 read pairs 
[I::dump_links_from_bam_file] 87 million records processed, 4491898 read pairs 
[I::dump_links_from_bam_file] 88 million records processed, 4544553 read pairs 
[I::dump_links_from_bam_file] 89 million records processed, 4596682 read pairs 
[I::dump_links_from_bam_file] 90 million records processed, 4648640 read pairs 
[I::dump_links_from_bam_file] 91 million records processed, 4701342 read pairs 
[I::dump_links_from_bam_file] 92 million records processed, 4754213 read pairs 
[I::dump_links_from_bam_file] 93 million records processed, 4805207 read pairs 
[I::dump_links_from_bam_file] 94 million records processed, 4856422 read pairs 
[I::dump_links_from_bam_file] 95 million records processed, 4908470 read pairs 
[I::dump_links_from_bam_file] 96 million records processed, 4959696 read pairs 
[I::dump_links_from_bam_file] 97 million records processed, 5011150 read pairs 
[I::dump_links_from_bam_file] 98 million records processed, 5061587 read pairs 
[I::dump_links_from_bam_file] 99 million records processed, 5113241 read pairs 
[I::dump_links_from_bam_file] dumped 5139015 read pairs: 5139015 intra links + 0 inter links 
[I::run_yahs] RAM total: 251.636GB
[I::run_yahs] RAM limit: 62.500GB
[I::contig_error_break] dist threshold for contig error break: 1000000
[I::contig_error_break] performed 1 round assembly error correction. Made 0 breaks 
[I::print_asm_stats] assembly stats:
[I::print_asm_stats]  N50: 298818 (n = 1164)
[I::print_asm_stats]  N90: 57430 (n = 4785)
[I::run_yahs] scaffolding round 1 resolution = 10000
[I::run_scaffolding] starting norm estimation...
[I::run_scaffolding] starting link estimation...
[I::inter_link_norms] using noise level 0.000000000000
[I::inter_link_norms] average link count: 0.000000000000 29410615.000000000000 0.000000000000
[I::run_scaffolding] starting scaffolding graph contruction...
[I::print_asm_stats] assembly stats:
[I::print_asm_stats]  N50: 298818 (n = 1164)
[I::print_asm_stats]  N90: 57430 (n = 4785)
[I::run_yahs] scaffolding round 2 resolution = 20000
[I::run_scaffolding] starting norm estimation...
[I::run_scaffolding] starting link estimation...
[I::inter_link_norms] using noise level 0.000000000000
[I::inter_link_norms] average link count: 0.000000000000 16683976.000000000000 0.000000000000
[I::run_scaffolding] starting scaffolding graph contruction...
[I::print_asm_stats] assembly stats:
[I::print_asm_stats]  N50: 298818 (n = 1164)
[I::print_asm_stats]  N90: 57430 (n = 4785)
[I::run_yahs] scaffolding round 3 resolution = 50000
[I::run_yahs] assembly N50 (298818) too small. End of scaffolding.
[I::main] writing FASTA file for scaffolds

**Comment by c-zhou** [comment]
Hi aureliendejode,

You could try to start a higher resolution (smaller values for `-r` option), e. g., `-r 5000, 10000, 20000, 50000,100000,200000,500000,1000000,2000000,5000000,10000000,20000000`. However, I would not suggest using HiC signal for scaffolding for such a fragmented assembly - HiC data is just not good at this. Even if you get some results, it could be error-prone to local incorrect orderings.

Best,
Chenxi

**Comment by c-zhou** [comment]
Hi @aureliendejode,

It might be too late, but I just realised your problem was similar to Issue #21. The BAM file you used was not sorted by read names.

In the latest commit. I made YaHS accept unsorted BAM as well.

I will close this issue.

Chenxi
