### ISSUE TITLE
 mark duplicates

### ISSUE THREAD

**Issue by guo-cheng** [c-zhou/yahs#19]
Hi Zhou

It's an excellent software. 
I want to know if I didn't use the Arima HiC, whether I need to mark duplicates.

Best wishes！

Guo-Cheng Li

**Comment by c-zhou** [comment]
Hi Guo-Cheng, 

Thanks for using YaHS.

This kind of falls outside of my area of expertise. From my understanding, in most cases, you are very unlikely to be wrong to mark duplicates.

Best,
Chenxi

**Comment by c-zhou** [comment]
I will now close this issue.
