### ISSUE TITLE
assembly N50 (12787427) too small. End of scaffolding

### ISSUE THREAD

**Issue by guo-cheng** [c-zhou/yahs#22]
Hi Chen Xi

I sorted my BAM file by read names. The log file :
[I::dump_links_from_bam_file] 314 million records processed, 154274614 read pairs
assembly N50 (12787427) too small. End of scaffolding.

I think my genome contig is relative complete. I changed a lot of times parameters and inputs.
But the log also says **End of scaffolding**

Best !
Guo Cheng

[I::dump_links_from_bam_file] 314 million records processed, 154274614 read pairs
[I::dump_links_from_bam_file] dumped 154542127 read pairs: 95763255 intra links + 19261793 inter links
[I::run_yahs] RAM total: 187.400GB
[I::run_yahs] RAM limit: 1.083GB
[I::contig_error_break] dist threshold for contig error break: 1000000
[I::contig_error_break] performed 2 round assembly error correction. Made 9 breaks
[I::print_asm_stats] assembly stats:
[I::print_asm_stats] N50: 10803692 (n = 16)
[I::print_asm_stats] N90: 3852502 (n = 40)
[I::run_yahs] scaffolding round 1 resolution = 10000
[I::run_scaffolding] starting norm estimation...
[I::run_scaffolding] starting link estimation...
[I::inter_link_norms] using noise level 0.006897546529
[I::inter_link_norms] average link count: 11438.389371032354 5037531.000000000000 0.002270634041
[I::run_scaffolding] starting scaffolding graph contruction...
[I::print_asm_stats] assembly stats:
[I::print_asm_stats] N50: 11471531 (n = 16)
[I::print_asm_stats] N90: 4097666 (n = 36)
[I::run_yahs] scaffolding round 2 resolution = 20000
[I::run_scaffolding] starting norm estimation...
[I::run_scaffolding] starting link estimation...
[I::inter_link_norms] using noise level 0.029375186223
[I::inter_link_norms] average link count: 8939.121059218443 5723120.000000000000 0.001561931439
[I::run_scaffolding] starting scaffolding graph contruction...
[I::print_asm_stats] assembly stats:
[I::print_asm_stats] N50: 11595593 (n = 16)
[I::print_asm_stats] N90: 4205433 (n = 34)
[I::run_yahs] scaffolding round 3 resolution = 50000
[I::run_scaffolding] starting norm estimation...
[I::run_scaffolding] starting link estimation...
[I::inter_link_norms] using noise level 0.251675046921
[I::inter_link_norms] average link count: 5536.808779269413 3736534.000000000000 0.001481803398
[I::run_scaffolding] starting scaffolding graph contruction...
[I::print_asm_stats] assembly stats:
[I::print_asm_stats] N50: 11870607 (n = 15)
[I::print_asm_stats] N90: 4312936 (n = 33)
[I::run_yahs] scaffolding round 4 resolution = 100000
[I::run_scaffolding] starting norm estimation...
[I::run_scaffolding] starting link estimation...
[I::inter_link_norms] using noise level 1.878855434932
[I::inter_link_norms] average link count: 2203.180432421749 1871969.000000000000 0.001176932114
[I::run_scaffolding] starting scaffolding graph contruction...
[I::print_asm_stats] assembly stats:
[I::print_asm_stats] N50: 11870607 (n = 15)
[I::print_asm_stats] N90: 4205433 (n = 34)
[I::run_yahs] scaffolding round 5 resolution = 200000
[I::run_scaffolding] starting norm estimation...
[I::run_scaffolding] starting link estimation...
[I::inter_link_norms] using noise level 0.969795918367
[I::inter_link_norms] average link count: 4.085832445017 1225.000000000000 0.003335373425
[I::run_scaffolding] starting scaffolding graph contruction...
[I::print_asm_stats] assembly stats:
[I::print_asm_stats] N50: 12200854 (n = 15)
[I::print_asm_stats] N90: 5874100 (n = 32)
[I::run_yahs] scaffolding round 6 resolution = 500000
[I::run_scaffolding] starting norm estimation...
[I::run_scaffolding] starting link estimation...
[I::inter_link_norms] using noise level 45.104278914056
[I::inter_link_norms] average link count: 75.156734682509 69779.000000000000 0.001077068096
[I::run_scaffolding] starting scaffolding graph contruction...
[I::print_asm_stats] assembly stats:
[I::print_asm_stats] N50: 12685561 (n = 15)
[I::print_asm_stats] N90: 6205944 (n = 31)
[I::run_yahs] scaffolding round 7 resolution = 1000000
[I::run_scaffolding] starting norm estimation...
[I::run_scaffolding] starting link estimation...
[I::inter_link_norms] using noise level 172.238464437625
[I::inter_link_norms] average link count: 25.031645569828 16459.000000000000 0.001520848507
[I::run_scaffolding] starting scaffolding graph contruction...
[I::print_asm_stats] assembly stats:
[I::print_asm_stats] N50: 12787427 (n = 14)
[I::print_asm_stats] N90: 6205944 (n = 31)
[I::run_yahs] scaffolding round 8 resolution = 2000000
[I::run_yahs] assembly N50 (12787427) too small. End of scaffolding.
[I::main] writing FASTA file for scaffolds

**Comment by c-zhou** [comment]
Hi Guo-Cheng,

`assembly N50 (12787427) too small. End of scaffolding` is not an error message. The message suggests the scaffolding has been successfully run and it ended at 1Mb resolution. All scaffolding processes will end at a certain resolution. Your genome looks quite small (maybe a few hundred megabases?) and your assembly looks quite good (should have many chromosomal scale contigs). Do you know how many chromosomes in your species? You might generate a HiC contact map to check. You can also do some manual editing with JuicerBox or PretextMap where necessary.

Chenxi

**Comment by guo-cheng** [comment]
> Hi Guo-Cheng,
> 
> `assembly N50 (12787427) too small. End of scaffolding` is not an error message. The message suggests the scaffolding has been successfully run and it ended at 1Mb resolution. All scaffolding processes will end at a certain resolution. Your genome looks quite small (maybe a few hundred megabases?) and your assembly looks quite good (should have many chromosomal scale contigs). Do you know how many chromosomes in your species? You might generate a HiC contact map to check. You can also do some manual editing with JuicerBox or PretextMap where necessary.
> 
> Chenxi
Hi Chengxi,
Thank you for your reply. 

My sequencing species genome is about 400Mb and has 31 chromosome. The HiC coverage is 100X. Do you know how to elevation the scaffold contigunity. Is my HiC coverage not enough ?

**Comment by c-zhou** [comment]
Hi Guo-Cheng,

100x seems a reasonable HiC coverage for scaffolding. The log tells us 90% of the sequences were put into 31 chromosomes - your expected chromosome number, so approximately 10% (40Mb ) was left unplaced. It is very difficult to tell the reason without seeing the actual HiC contact map. From my guess, this is usually due to repeats and usually from the centromere regions, which is in general unresolvable solely with HiC data. If you do want to deal with these left pieces, you could try manual curation or generate some ultra-long reads to help scaffold as what has been done in assembling the human T2T genome.

Chenxi

**Comment by guo-cheng** [comment]
> Hi Guo-Cheng,
> 
> 100x seems a reasonable HiC coverage for scaffolding. The log tells us 90% of the sequences were put into 31 chromosomes - your expected chromosome number, so approximately 10% (40Mb ) was left unplaced. It is very difficult to tell the reason without seeing the actual HiC contact map. From my guess, this is usually due to repeats and usually from the centromere regions, which is in general unresolvable solely with HiC data. If you do want to deal with these left pieces, you could try manual curation or generate some ultra-long reads to help scaffold as what has been done in assembling the human T2T genome.
> 
> Chenxi

OK. I see. 
Thanks a lot.

Best wishs!
Guo Cheng
