### ISSUE TITLE
question about " juicer post "

### ISSUE THREAD

**Issue by Zoey1001** [c-zhou/yahs#23]
there is the command:
juicer post -o out_JBAT out_JBAT.review.assembly out_JBAT.liftover.agp contigs.fa
which means” Once completed editing, there should be a file named something like out_JBAT.review.assembly generated by Juicebox, which can be fed into juicer post command to generate AGP and FASTA files for the final genome assembly.”
however,i can not find the "juicer post "command after  installed the yahs-1.1a.2 and juicer

**Comment by c-zhou** [comment]
Hi @Zoey1001,

It was implemented in the last commit. I have not tagged a release for it yet. You need to download the latest code from the main branch and install it.

Best,
Chenxi

**Comment by c-zhou** [comment]
By the way, if you did your curation with the older version YaHS, please read this https://github.com/c-zhou/yahs/issues/4#issuecomment-1153019912.

Chenxi
