### ISSUE TITLE
agp_to_fasta fails on agp with header comments

### ISSUE THREAD

**Issue by abueg** [c-zhou/yahs#25]
Hello! 👋🏼

I was trying the agp_to_fasta tool included in the v1.1 yahs release (agp_to_fasta outputs version 1.0 though) and it seems to be failing on an AGP file that begins with header lines. I removed the header lines from the AGP and then the tool works perfectly.

```
[labueg@login04 /lustre/fs5/vgl/scratch/labueg/temp]$ $STORE/programs/yahs-1.1/agp_to_fasta
Usage: agp_to_fasta [options] <scaffolds.agp> <contigs.fa>
Options:
    -l INT            line width [60]
    -o STR            output to file [stdout]
    --version         show version number
[labueg@login04 /lustre/fs5/vgl/scratch/labueg/temp]$ $STORE/programs/yahs-1.1/agp_to_fasta mNycCou1_s1.agp mNycCou1_p1.fasta -o test
[E::write_fasta_file_from_agp] sequence ?w?N not found
[labueg@login04 /lustre/fs5/vgl/scratch/labueg/temp]$ head -n 1 mNycCou1_p1.fasta
>ptg000001l_1
[labueg@login04 /lustre/fs5/vgl/scratch/labueg/temp]$ head mNycCou1_s1.agp 
##agp-version	2.0
# Organism:  
# Platform:     
# Model:        
# Enzyme(s):    
# BioSample:    
# BioProject:   
# Obj_Name	Obj_Start	Obj_End	PartNum	Compnt_Type	CompntId_GapLength	CompntStart_GapType	CompntEnd_Linkage	Orientation_LinkageEvidence
Super-Scaffold_1	1	56613158	1	W	ptg000001l_1	1	56613158	+
Super-Scaffold_12	1	936489	1	W	ptg000097l_1	158389	1094877	-
[labueg@login04 /lustre/fs5/vgl/scratch/labueg/temp]$ grep -v "^#" mNycCou1_s1.agp > mNycCou1_s1.nocomment.agp
[labueg@login04 /lustre/fs5/vgl/scratch/labueg/temp]$ $STORE/programs/yahs-1.1/agp_to_fasta mNycCou1_s1.nocomment.agp mNycCou1_p1.fasta -o test
[I::main] Version: 1.0
[I::main] CMD: /lustre/fs5/vgl/store/labueg/programs/yahs-1.1/agp_to_fasta -o test mNycCou1_s1.nocomment.agp mNycCou1_p1.fasta
[I::main] Real time: 63.428 sec; CPU: 58.669 sec; Peak RSS: 2.815 GB
```

Just wanted to bring this up in case it would be helpful for the tool to account for headers in AGPs, thank you for developing it!

**Comment by c-zhou** [comment]
Thanks for bringing this up @abueg. I made a fix in the latest commit. I also add features to support the GAP identifier `U` and sequence components of unknown orientations (`-u` option). It now fully supports the standard [AGP format](https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/).

Chenxi

**Comment by abueg** [comment]
Hi Chenxi,

Thank you for your response! Sorry to bother you again, but I gave the new version a try by building from source on your latest commit, but now it is returning a different error when I am using it on the same file as before (the one with header comments):

```
[labueg@login04 /lustre/fs5/vgl/scratch/labueg/temp]$ $STORE/programs/yahs/agp_to_fasta --version
1.1
[labueg@login04 /lustre/fs5/vgl/scratch/labueg/temp]$ $STORE/programs/yahs/agp_to_fasta mNycCou1_s1.agp mNycCou1_p1.fasta -o test
[E::write_fasta_file_from_agp] sequence Compnt_Type not found
[labueg@login04 /lustre/fs5/vgl/scratch/labueg/temp]$ head mNycCou1_s1.agp 
##agp-version	2.0
# Organism:  
# Platform:     
# Model:        
# Enzyme(s):    
# BioSample:    
# BioProject:   
# Obj_Name	Obj_Start	Obj_End	PartNum	Compnt_Type	CompntId_GapLength	CompntStart_GapType	CompntEnd_Linkage	Orientation_LinkageEvidence
Super-Scaffold_1	1	56613158	1	W	ptg000001l_1	1	56613158	+
Super-Scaffold_12	1	936489	1	W	ptg000097l_1	158389	1094877	-
```

**Comment by c-zhou** [comment]
Hi @abueg,

Thanks for letting me know. It was a bug and should be fixed in the latest commit.

Chenxi

**Comment by abueg** [comment]
Hi @c-zhou ,

Thanks for pushing the fix -- I just gave it a try on the same files and it worked like a charm!
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/48773001/177843011-276fa558-605b-4c85-919b-d45b9c187ac4.png">

I wanted to bring something else up regarding AGPs -- @astrovsky01 and the Galaxy team are working at wrapping yahs to work in Galaxy, and have run into an issue where their [AGP format](https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/) sniffer is detecting the yahs AGP as incorrectly formatted. 

This is because column `9b` is `na` (for usage when linkage is not being asserted, i.e., when `8b` is `no` as well), implying there is no evidence for linkage assertion, when column `8b` is `yes` meaning that these gaps are actually asserting linkage, based on the evidence of HiC information. 

Do you think it would be possible for yahs to output the linkage evidence (column `9b`) as `proximity_ligation`, as that is the category specified for Hi-C & related technologies by the AGP specification?

Example of yahs AGP with the column fields that I mentioned:
```
scaffold_1	1	293717	1	W	Super-Scaffold_2835	1	293717	+
scaffold_1	293718	293917	2	N	200	scaffold	yes	na
scaffold_1	293918	335564	3	W	h1tg004585l_obj	1	41647	+
scaffold_1	335565	335764	4	N	200	scaffold	yes	na
scaffold_1	335765	433284	5	W	h1tg000801l_obj	1	97520	-
```

Let me know what you think, and thanks again for working on this great tool!

Best,
Linelle

**Comment by c-zhou** [comment]
Hi Linelle,

It sounds sensible to me and I do not see any potential compatibility problems. I changed the linkage evidence identifier to `proximity_ligation` in the latest commit.

Best,
Chenxi

**Comment by astrovsky01** [comment]
Thank you Chenxi! Is there any way this fix and the one for the header could be added to a release, so it can be integrated into the bioconda version?

Alex

**Comment by c-zhou** [comment]
Hi Alex, I tagged [v1.2a](https://github.com/c-zhou/yahs/releases/tag/v1.2a). Cheers, Chenxi

**Comment by abueg** [comment]
Hi @c-zhou , thank you so much for your help + releasing the tag, that did the trick for getting bioconda up to date -- feel free to close this issue, thanks again!
