### ISSUE TITLE
Starting scaffolding graph contruction

### ISSUE THREAD

**Issue by PengjuZ** [c-zhou/yahs#26]
Hi Chenxi,

Thank you for writing such a handy tool.

However, when i used the yahs (version is 1.2a) for 1.1g genomes. it causes a segmentation fault:

[I::find_re_from_seqs] NO. restriction enzyme cutting sites found in sequences: 5043048
[I::find_re_from_seqs] restriction enzyme cutting sites density: 0.004520
[I::run_yahs] RAM total: 376.153GB
[I::run_yahs] RAM limit: 356.828GB
[I::contig_error_break] dist threshold for contig error break: 19830000
[I::contig_error_break] performed 5 round assembly error correction. Made 52 breaks 
[I::print_asm_stats] assembly stats:
[I::print_asm_stats]  N50: 52262000 (n = 7)
[I::print_asm_stats]  N90: 6523145 (n = 30)
[I::run_yahs] scaffolding round 1 resolution = 10000
[I::run_scaffolding] starting norm estimation...
[I::run_scaffolding] starting link estimation...
[I::inter_link_norms] using noise level 0.001048956614
[I::inter_link_norms] average link count: 4164.498389389475 1892474.000000000000 0.002200557783
[I::run_scaffolding] starting scaffolding graph contruction...
Segmentation fault (core dumped)

what's the problem?

Regards,
PengjuZ

**Comment by c-zhou** [comment]
Hi @PengjuZ,

Thanks for using YaHS. I cannot tell what the problem is without further information. Could you show me a list of the files that have been generated? If possible, it would be very helpful to run it in debug mode. You need to run `gdb yahs` and then run `run $all_your_yahs_parameters` in the debugger console.

Best,
Chenxi

**Comment by PengjuZ** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thanks for your responding! As your suggestion, i run debug mode.
        Program received signal SIGSEGV, Segmentation fault.0x00002aaaab065be3 in __memcpy_sse2 () from /lib64/libc.so.6Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64The files generated as follows:Best,PengjuZ
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zhaopengju2014
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 7/16/2022 ***@***.***> wrote： 



Hi @PengjuZ,
Thanks for using YaHS. I cannot tell what the problem is without further information. Could you show me a list of the files that have been generated? If possible, it would be very helpful to run it in debug mode. You need to run gdb yahs and then run run $all_your_yahs_parameters in the debugger console.
Best,
Chenxi

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by c-zhou** [comment]
Hi @PengjuZ, the message does not display correctly here. Chenxi

**Comment by PengjuZ** [comment]
> Hi @PengjuZ, the message does not display correctly here. Chenxi

Sorry, i resend it.

Thanks for your responding! As your suggestion, i run debug mode.

Program received signal SIGSEGV, Segmentation fault.
0x00002aaaab065be3 in __memcpy_sse2 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64

The files generated as follows:
![image](https://user-images.githubusercontent.com/109416356/179357177-2dd56f64-e7c2-4961-a014-87a9bb5c7604.png)

**Comment by c-zhou** [comment]
Hi @PengjuZ,

Thanks for sharing the information. Unfortunately, I still do not have enough (debug) information to identify the problem. Looking at the output files, I guess something went wrong during the scaffolding error break. You can try to run YaHS with `--no-scaffold-ec` option and see if the segfault persists.

The log info shows `dist threshold for contig error break: 19830000`, suggesting there are 20% of HiC read pairs with greater than 19.83Mb separating distance, which does not seem right to me. I suggest generating a HiC contact map for the contigs to have a check.

Another thing I want to mention is that I restructured the code a little bit in version 1.2a. Not sure if I introduced some bugs. You might give the older version [v1.1](https://github.com/c-zhou/yahs/releases/tag/v1.1) a try.

Best,
Chenxi

**Comment by c-zhou** [comment]
Hello @PengjuZ,

I found a bug that could cause segfault with unsorted or coordinate-sorted BAM inputs. It should not affect queryname-sorted BAM or BED input. I fixed it in the latest commit. If you did use an unsorted or coordinate-sorted BAM input, you might give it a go. You need to discard the BIN file and start from the BAM file.

Best,
Chenxi

**Comment by PengjuZ** [comment]
> Hello @PengjuZ,
> 
> I found a bug that could cause segfault with unsorted or coordinate-sorted BAM inputs. It should not affect queryname-sorted BAM or BED input. I fixed it in the latest commit. If you did use an unsorted or coordinate-sorted BAM input, you might give it a go. You need to discard the BIN file and start from the BAM file.
> 
> Best, Chenxi


Thanks for your replying! I sorted the BAM inputs with queryname (-n). this Bam input is well used in Salsa pipeline. 
I also used the BAM file with -p 10 instead of the BIN file. but unfortunately it same errors.

**Comment by c-zhou** [comment]
Thanks PengjuZ. Yeah, if your BAM file is not sorted by queryname, there should be a warning message `BAM file is not sorted by read name. Filtering by mapping quality suppressed` at the very beginning of the log file.

I am wondering if you have tried to use the BED file (the one used for SALSA) as input, although the queryname sorted BAM and BED file should be equivalent.

Best,
Chenxi

**Comment by yoshihikosuzuki** [comment]
I came across with probably the same bug, and I found that by changing the optimization flag in Makefile from `-O3` to `-O0` yahs finishes without errors. If this resolves your problem as well, then maybe it is related to some difference in compiler or architecture.

**Comment by PengjuZ** [comment]
> I came across with probably the same bug, and I found that by changing the optimization flag in Makefile from `-O3` to `-O0` yahs finishes without errors. If this resolves your problem as well, then maybe it is related to some difference in compiler or architecture.

Thanks  for your sharing . i will try it!

**Comment by alexcorm** [comment]
I had the same issue and @yoshihikosuzuki 's solution worked for me!

Thanks

**Comment by PengjuZ** [comment]
> I came across with probably the same bug, and I found that by changing the optimization flag in Makefile from `-O3` to `-O0` yahs finishes without errors. If this resolves your problem as well, then maybe it is related to some difference in compiler or architecture.

It also worked for me! Thanks @yoshihikosuzuki

**Comment by c-zhou** [comment]
Thanks all. I will try to figure out the underlying causes. For now, I have changed the makefile to -O0.

Chenxi
