### ISSUE TITLE
Yahs run doesn't complete

### ISSUE THREAD

**Issue by caiobrunharo** [c-zhou/yahs#27]
Hi

I am trying to run yahs on a genome assembly generated with hifiasm. It looks like the run is never completed. See the log below. Any thoughts on what could be causing it? The genome is indexed with samtools faidx and the BED was generated using the Arima Genomics guidelines. 

My command: yahs poa_with_HiC.asm.hic.hap1.p_ctg.fa paired_RG_duplicates_sorted_final.bed -e GATC,TNA,ANT,TA >./output_yahs.log 2>&1

Thank you!

[Linux@vaughan yahs]$ cat output_yahs
[I::find_re_from_seqs] NO. restriction enzyme cutting sites found in sequences: 553814228
[I::find_re_from_seqs] restriction enzyme cutting sites density: 0.396177
[I::main] dump hic links (BED) to binary file yahs.out.bin
[I::dump_links_from_bed_file] 1 million records processed, 499999 read pairs
[I::dump_links_from_bed_file] 2 million records processed, 999999 read pairs
[I::dump_links_from_bed_file] 3 million records processed, 1499999 read pairs
[I::dump_links_from_bed_file] 4 million records processed, 1999999 read pairs
[I::dump_links_from_bed_file] 5 million records processed, 2499999 read pairs
[I::dump_links_from_bed_file] 6 million records processed, 2999999 read pairs
[I::dump_links_from_bed_file] 7 million records processed, 3499999 read pairs
[I::dump_links_from_bed_file] 8 million records processed, 3999999 read pairs
[I::dump_links_from_bed_file] 9 million records processed, 4499999 read pairs
[I::dump_links_from_bed_file] 10 million records processed, 4999999 read pairs
[I::dump_links_from_bed_file] 11 million records processed, 5499999 read pairs
[I::dump_links_from_bed_file] 12 million records processed, 5999999 read pairs
[I::dump_links_from_bed_file] 13 million records processed, 6499999 read pairs
[I::dump_links_from_bed_file] 14 million records processed, 6999999 read pairs
[I::dump_links_from_bed_file] 15 million records processed, 7499999 read pairs
[I::dump_links_from_bed_file] 16 million records processed, 7999999 read pairs
[I::dump_links_from_bed_file] 17 million records processed, 8499999 read pairs
[I::dump_links_from_bed_file] 18 million records processed, 8999999 read pairs
[I::dump_links_from_bed_file] 19 million records processed, 9499999 read pairs
[I::dump_links_from_bed_file] 20 million records processed, 9999999 read pairs
[I::dump_links_from_bed_file] 21 million records processed, 10499999 read pairs
[I::dump_links_from_bed_file] 22 million records processed, 10999999 read pairs
[I::dump_links_from_bed_file] 23 million records processed, 11499999 read pairs
[I::dump_links_from_bed_file] 24 million records processed, 11999999 read pairs
[I::dump_links_from_bed_file] 25 million records processed, 12499999 read pairs
[I::dump_links_from_bed_file] 26 million records processed, 12999999 read pairs
[I::dump_links_from_bed_file] 27 million records processed, 13499999 read pairs
[I::dump_links_from_bed_file] 28 million records processed, 13999999 read pairs
[I::dump_links_from_bed_file] 29 million records processed, 14499999 read pairs
[I::dump_links_from_bed_file] 30 million records processed, 14999999 read pairs
[I::dump_links_from_bed_file] 31 million records processed, 15499999 read pairs
[I::dump_links_from_bed_file] 32 million records processed, 15999999 read pairs
[I::dump_links_from_bed_file] 33 million records processed, 16499999 read pairs
[I::dump_links_from_bed_file] 34 million records processed, 16999999 read pairs
[I::dump_links_from_bed_file] 35 million records processed, 17499999 read pairs
[I::dump_links_from_bed_file] 36 million records processed, 17999999 read pairs
[I::dump_links_from_bed_file] 37 million records processed, 18499999 read pairs
[I::dump_links_from_bed_file] 38 million records processed, 18999999 read pairs
[I::dump_links_from_bed_file] 39 million records processed, 19499999 read pairs
[I::dump_links_from_bed_file] 40 million records processed, 19999999 read pairs
[I::dump_links_from_bed_file] 41 million records processed, 20499999 read pairs
[I::dump_links_from_bed_file] 42 million records processed, 20999999 read pairs
[I::dump_links_from_bed_file] 43 million records processed, 21499999 read pairs
[I::dump_links_from_bed_file] 44 million records processed, 21999999 read pairs
[I::dump_links_from_bed_file] 45 million records processed, 22499999 read pairs
[I::dump_links_from_bed_file] 46 million records processed, 22999999 read pairs
[I::dump_links_from_bed_file] 47 million records processed, 23499999 read pairs
[I::dump_links_from_bed_file] 48 million records processed, 23999999 read pairs
[I::dump_links_from_bed_file] 49 million records processed, 24499999 read pairs
[I::dump_links_from_bed_file] 50 million records processed, 24999999 read pairs
[I::dump_links_from_bed_file] 51 million records processed, 25499999 read pairs
[I::dump_links_from_bed_file] 52 million records processed, 25999999 read pairs
[I::dump_links_from_bed_file] 53 million records processed, 26499999 read pairs
[I::dump_links_from_bed_file] 54 million records processed, 26999999 read pairs
[I::dump_links_from_bed_file] 55 million records processed, 27499999 read pairs
[I::dump_links_from_bed_file] 56 million records processed, 27999999 read pairs
[I::dump_links_from_bed_file] 57 million records processed, 28499999 read pairs
[I::dump_links_from_bed_file] 58 million records processed, 28999999 read pairs
[I::dump_links_from_bed_file] 59 million records processed, 29499999 read pairs
[I::dump_links_from_bed_file] 60 million records processed, 29999999 read pairs
[I::dump_links_from_bed_file] 61 million records processed, 30499999 read pairs
[I::dump_links_from_bed_file] 62 million records processed, 30999999 read pairs
[I::dump_links_from_bed_file] 63 million records processed, 31499999 read pairs
[I::dump_links_from_bed_file] 64 million records processed, 31999999 read pairs
[I::dump_links_from_bed_file] 65 million records processed, 32499999 read pairs
[I::dump_links_from_bed_file] 66 million records processed, 32999999 read pairs
[I::dump_links_from_bed_file] 67 million records processed, 33499999 read pairs
[I::dump_links_from_bed_file] 68 million records processed, 33999999 read pairs
[I::dump_links_from_bed_file] 69 million records processed, 34499999 read pairs
[I::dump_links_from_bed_file] 70 million records processed, 34999999 read pairs
[I::dump_links_from_bed_file] 71 million records processed, 35499999 read pairs
[I::dump_links_from_bed_file] 72 million records processed, 35999999 read pairs
[I::dump_links_from_bed_file] 73 million records processed, 36499999 read pairs
[I::dump_links_from_bed_file] 74 million records processed, 36999999 read pairs
[I::dump_links_from_bed_file] 75 million records processed, 37499999 read pairs
[I::dump_links_from_bed_file] 76 million records processed, 37999999 read pairs
[I::dump_links_from_bed_file] 77 million records processed, 38499999 read pairs
[I::dump_links_from_bed_file] 78 million records processed, 38999999 read pairs
[I::dump_links_from_bed_file] 79 million records processed, 39499999 read pairs
[I::dump_links_from_bed_file] 80 million records processed, 39999999 read pairs
[I::dump_links_from_bed_file] 81 million records processed, 40499999 read pairs
[I::dump_links_from_bed_file] 82 million records processed, 40999999 read pairs
[I::dump_links_from_bed_file] 83 million records processed, 41499999 read pairs
[I::dump_links_from_bed_file] 84 million records processed, 41999999 read pairs
[I::dump_links_from_bed_file] 85 million records processed, 42499999 read pairs
[I::dump_links_from_bed_file] 86 million records processed, 42999999 read pairs
[I::dump_links_from_bed_file] 87 million records processed, 43499999 read pairs
[I::dump_links_from_bed_file] 88 million records processed, 43999999 read pairs
[I::dump_links_from_bed_file] 89 million records processed, 44499999 read pairs
[I::dump_links_from_bed_file] 90 million records processed, 44999999 read pairs
[I::dump_links_from_bed_file] 91 million records processed, 45499999 read pairs
[I::dump_links_from_bed_file] 92 million records processed, 45999999 read pairs
[I::dump_links_from_bed_file] 93 million records processed, 46499999 read pairs
[I::dump_links_from_bed_file] 94 million records processed, 46999999 read pairs
[I::dump_links_from_bed_file] 95 million records processed, 47499999 read pairs
[I::dump_links_from_bed_file] 96 million records processed, 47999999 read pairs
[I::dump_links_from_bed_file] 97 million records processed, 48499999 read pairs
[I::dump_links_from_bed_file] 98 million records processed, 48999999 read pairs
[I::dump_links_from_bed_file] 99 million records processed, 49499999 read pairs
[I::dump_links_from_bed_file] 100 million records processed, 49999999 read pairs
[I::dump_links_from_bed_file] 101 million records processed, 50499999 read pairs
[I::dump_links_from_bed_file] 102 million records processed, 50999999 read pairs
[I::dump_links_from_bed_file] 103 million records processed, 51499999 read pairs
[I::dump_links_from_bed_file] 104 million records processed, 51999999 read pairs
[I::dump_links_from_bed_file] 105 million records processed, 52499999 read pairs
[I::dump_links_from_bed_file] 106 million records processed, 52999999 read pairs
[I::dump_links_from_bed_file] 107 million records processed, 53499999 read pairs
[I::dump_links_from_bed_file] 108 million records processed, 53999999 read pairs
[I::dump_links_from_bed_file] 109 million records processed, 54499999 read pairs
[I::dump_links_from_bed_file] 110 million records processed, 54999999 read pairs
[I::dump_links_from_bed_file] 111 million records processed, 55499999 read pairs
[I::dump_links_from_bed_file] 112 million records processed, 55999999 read pairs
[I::dump_links_from_bed_file] 113 million records processed, 56499999 read pairs
[I::dump_links_from_bed_file] 114 million records processed, 56999999 read pairs
[I::dump_links_from_bed_file] 115 million records processed, 57499999 read pairs
[I::dump_links_from_bed_file] 116 million records processed, 57999999 read pairs
[I::dump_links_from_bed_file] 117 million records processed, 58499999 read pairs
[I::dump_links_from_bed_file] 118 million records processed, 58999999 read pairs
[I::dump_links_from_bed_file] 119 million records processed, 59499999 read pairs
[I::dump_links_from_bed_file] 120 million records processed, 59999999 read pairs
[I::dump_links_from_bed_file] 121 million records processed, 60499999 read pairs
[I::dump_links_from_bed_file] 122 million records processed, 60999999 read pairs
[I::dump_links_from_bed_file] 123 million records processed, 61499999 read pairs
[I::dump_links_from_bed_file] 124 million records processed, 61999999 read pairs
[I::dump_links_from_bed_file] 125 million records processed, 62499999 read pairs
[I::dump_links_from_bed_file] 126 million records processed, 62999999 read pairs
[I::dump_links_from_bed_file] 127 million records processed, 63499999 read pairs
[I::dump_links_from_bed_file] 128 million records processed, 63999999 read pairs
[I::dump_links_from_bed_file] 129 million records processed, 64499999 read pairs
[I::dump_links_from_bed_file] 130 million records processed, 64999999 read pairs
[I::dump_links_from_bed_file] 131 million records processed, 65499999 read pairs
[I::dump_links_from_bed_file] 132 million records processed, 65999999 read pairs
[I::dump_links_from_bed_file] 133 million records processed, 66499999 read pairs
[I::dump_links_from_bed_file] 134 million records processed, 66999999 read pairs
[I::dump_links_from_bed_file] 135 million records processed, 67499999 read pairs
[I::dump_links_from_bed_file] 136 million records processed, 67999999 read pairs
[I::dump_links_from_bed_file] 137 million records processed, 68499999 read pairs
[I::dump_links_from_bed_file] 138 million records processed, 68999999 read pairs
[I::dump_links_from_bed_file] 139 million records processed, 69499999 read pairs
[I::dump_links_from_bed_file] 140 million records processed, 69999999 read pairs
[I::dump_links_from_bed_file] 141 million records processed, 70499999 read pairs
[I::dump_links_from_bed_file] 142 million records processed, 70999999 read pairs
[I::dump_links_from_bed_file] 143 million records processed, 71499999 read pairs
[I::dump_links_from_bed_file] 144 million records processed, 71999999 read pairs
[I::dump_links_from_bed_file] 145 million records processed, 72499999 read pairs
[I::dump_links_from_bed_file] 146 million records processed, 72999999 read pairs
[I::dump_links_from_bed_file] 147 million records processed, 73499999 read pairs
[I::dump_links_from_bed_file] 148 million records processed, 73999999 read pairs
[I::dump_links_from_bed_file] 149 million records processed, 74499999 read pairs
[I::dump_links_from_bed_file] 150 million records processed, 74999999 read pairs
[I::dump_links_from_bed_file] 151 million records processed, 75499999 read pairs
[I::dump_links_from_bed_file] 152 million records processed, 75999999 read pairs
[I::dump_links_from_bed_file] 153 million records processed, 76499999 read pairs
[I::dump_links_from_bed_file] 154 million records processed, 76999999 read pairs
[I::dump_links_from_bed_file] 155 million records processed, 77499999 read pairs
[I::dump_links_from_bed_file] 156 million records processed, 77999999 read pairs
[I::dump_links_from_bed_file] 157 million records processed, 78499999 read pairs
[I::dump_links_from_bed_file] 158 million records processed, 78999999 read pairs
[I::dump_links_from_bed_file] 159 million records processed, 79499999 read pairs
[I::dump_links_from_bed_file] 160 million records processed, 79999999 read pairs
[I::dump_links_from_bed_file] 161 million records processed, 80499999 read pairs
[I::dump_links_from_bed_file] dumped 80821099 read pairs from 161642198 records: 42809896 intra links + 38011203 inter links
[I::run_yahs] RAM total: 2015.189GB
[I::run_yahs] RAM limit: 1670.230GB
[I::contig_error_break] dist threshold for contig error break: 9900000
[I::contig_error_break] performed 2 round assembly error correction. Made 10 breaks
[I::print_asm_stats] assembly stats:
[I::print_asm_stats]  N50: 79612346 (n = 6)
[I::print_asm_stats]  N90: 11622114 (n = 24)
[I::print_asm_stats]  N100: 2000 (n = 905)
[I::run_yahs] scaffolding round 1 resolution = 10000
[I::run_scaffolding] starting norm estimation...
[I::run_scaffolding] starting link estimation...
[I::inter_link_norms] using noise level 0.000
[I::inter_link_norms] average link count: 981.501 3254199.000 0.000
[I::run_scaffolding] starting scaffolding graph contruction...
        Full Command:                      /nfs4/ROOTS/Brunharo_Lab/poa_genome_assembly/yahs/yahs/yahs poa_with_HiC.asm.hic.hap1.p_ctg.fa paired_RG_duplicates_sorted_final.bed -e GATC,TNA,ANT,TA
        Memory (kb):                       6942544
        # SWAP  (freq):                    0
        # Waits (freq):                    4631
        CPU (percent):                     66%
        Time (seconds):                    253.25
        Time (hh:mm:ss.ms):                4:13.25
        System CPU Time (seconds):         3.34
        User   CPU Time (seconds):         166.17

**Comment by c-zhou** [comment]
Hi @caiobrunharo,

Could you rebuild the program with `make clean; make debug` and rerun it. This will show more debug information to help identify the problem. The preprocess seems fine, so it should be fine to use the output BIN file which will save you some time.

Best,
Chenxi

**Comment by caiobrunharo** [comment]
Chenxi

Thank you for your response. Unfortunately, the analysis still doesn't complete. There is additional information in the log file, but I am not sure how to interpret it. I am only copying the last part of the log, as the beginning is identical to what I sent in my first message. Any thoughts?

Thanks
Caio


[I::dump_links_from_bed_file] 161 million records processed, 80499999 read pairs
[I::dump_links_from_bed_file] dumped 80821099 read pairs from 161642198 records: 42809896 intra links + 38011203 inter links
[I::run_yahs] RAM total: 2015.189GB
[I::run_yahs] RAM limit: 703.744GB
[DEBUG::run_yahs] perform contig error break...
[DEBUG::estimate_dist_thres_from_file] 80821099 read pairs processed, intra links: 42809896
[I::contig_error_break] dist threshold for contig error break: 9900000
[DEBUG::link_mat_from_file] 80821099 read pairs processed, intra links: 34248014
[DEBUG::contig_error_break] number contig breaks in round 1: 10
[DEBUG::link_mat_from_file] 80821099 read pairs processed, intra links: 34247135
[DEBUG::contig_error_break] number contig breaks in round 2: 0
[I::contig_error_break] performed 2 round assembly error correction. Made 10 breaks
[DEBUG::run_yahs] contig error break done
[I::print_asm_stats] assembly stats:
[I::print_asm_stats] N10: 150494894 (n = 1)
[I::print_asm_stats] N20: 137377455 (n = 2)
[I::print_asm_stats] N30: 112422486 (n = 4)
[I::print_asm_stats] N40: 109563119 (n = 5)
[I::print_asm_stats] N50: 79612346 (n = 6)
[I::print_asm_stats] N60: 57773519 (n = 8)
[I::print_asm_stats] N70: 39473998 (n = 11)
[I::print_asm_stats] N80: 28936905 (n = 16)
[I::print_asm_stats] N90: 11622114 (n = 24)
[I::print_asm_stats] N100: 2000 (n = 905)
[I::run_yahs] scaffolding round 1 resolution = 10000
[I::run_scaffolding] starting norm estimation...
[DEBUG::intra_link_mat_from_file] 80821099 read pairs processed, 42809017 intra links
[I::run_scaffolding] starting link estimation...
[DEBUG::inter_link_mat_from_file] 80821099 read pairs processed, 37997911 inter links
[DEBUG::inter_link_mat_from_file] within radius 15: 18292
[I::inter_link_norms] using noise level 0.000
[I::inter_link_norms] average link count: 981.501 3254199.000 0.000
[I::run_scaffolding] starting scaffolding graph contruction...
[DEBUG::run_yahs] perform scaffold error break
        Full Command:                      /nfs4/ROOTS/Brunharo_Lab/poa_genome_assembly/yahs/yahs/yahs poa_with_HiC.asm.hic.hap1.p_ctg.fa paired_RG_duplicates_sorted_final.bed -e GATC,TNA,ANT,TA

**Comment by c-zhou** [comment]
Hi Caio,

Thanks for sharing the results.

Yeah, it is still hard to tell what the problem is. The program hung in the scaffold error break step. Is it possible that you can send me the data file so I can have a look? I need the BIN file generated by the program (yahs.out.bin) and the FASTA index (poa_with_HiC.asm.hic.hap1.p_ctg.fa.fai) file. I do not need the FASTA file. You can drop me an email at cz370@cam.ac.uk for data sharing issues.

Best,
Chenxi

**Comment by caiobrunharo** [comment]
Chenxi

Thank you again for your assistance. As you indicated, it was indeed an issue with the IO in the cluster. I was able to run yahs locally in less than 10 min and the results were great.

./yahs my_genome.fa my_genome.bed -e GATC,TNA,ANT,TA >./output_yahs.log 2>&1

Thank you!
