### ISSUE TITLE
segfault in sd_coordinate_conversion

### ISSUE THREAD

**Issue by esrice** [c-zhou/yahs#28]
I'm getting a segmentation fault in a different place than any of the other ones reported. This happens in both v1.1 and v1.2a. I'm giving it a qname-sorted bed file. I actually have ~500GB RAM reserved on my cluster node. I also tried running with the smaller "-r" numbers removed to cut down on memory usage as suggested, but it never changes the number shown as "RAM limit" or makes the segfault go away. Same with `-l 10000`.

Here is the gdb output when running v1.2a with no additional arguments (`yahs contigs.fa aln.bed`):
```
[I::main] dump hic links (BED) to binary file yahs.out.bin
[I::dump_links_from_bed_file] 1 million records processed, 499999 read pairs
...
[I::dump_links_from_bed_file] 77 million records processed, 38499999 read pairs
[I::dump_links_from_bed_file] dumped 38770084 read pairs from 77540168 records: 34892804 intra links + 3877280 inter links
[I::run_yahs] RAM total: 503.634GB
[I::run_yahs] RAM limit: 308.463GB

Program received signal SIGSEGV, Segmentation fault.
0x0000555555568fd8 in sd_coordinate_conversion (d=0x555555588020, id=1199, pos=11248779,
    s=0x7fffffffc434, p=0x7ffffffeb420, count_gap=0)
```

Let me know if there's any other information I can provide! Thanks!

**Comment by c-zhou** [comment]
Hi Edward,

The gdb output `sd_coordinate_conversion (d=0x555555588020, id=1199, pos=11248779, s=0x7fffffffc434, p=0x7ffffffeb420, count_gap=0)` indicates the program tried to access position 11248779 on contig 1199 (should be the 1200th contig in your contig file). Could you please first help check the length of that contig?

Best,
Chenxi

**Comment by esrice** [comment]
Hi Chenxi,

Thanks for your super fast response. That contig only has 11248771, so I think my awk script to convert from pairs format (default chromap output) to bed is at fault.

Would you be open to a PR with a helpful error message when this happens instead of a segfault?

Thanks,
Edward

**Comment by esrice** [comment]
Oh, this doesn't seem to happen in v1.2a.1, never mind. Thanks again!
