### ISSUE TITLE
JBAT reference missing

### ISSUE THREAD

**Issue by dudcha** [c-zhou/yahs#30]
Please reference the JBAT paper (Dudchenko et Al bioRxiv 2018) and the genome assembly cookbook (dnazoo.org/methods) in the JBAT section of the README.

**Comment by c-zhou** [comment]
Hi @dudcha

I added "You can generate a HiC contact map file that can be loaded by Juicebox (JBAT, [Dudchenko et al. 2018](https://www.biorxiv.org/content/10.1101/254797v1)) for manual editing..." and "You can find more information about manual editing with Juicebox [here](https://www.dnazoo.org/methods) and [Issue 4](https://github.com/c-zhou/yahs/issues/4)".

Chenxi

**Comment by c-zhou** [comment]
I will close this if no more problems. Chenxi
