### ISSUE TITLE
-e restriction enzyme cutting sites for HindIII

### ISSUE THREAD

**Issue by Johnsonzcode** [c-zhou/yahs#33]
Hi @c-zhou 
It is a almost perfect scaffolding tools, it works on avian, but I don't konw how to set `-e` for HindIII enzyme.
![image](https://user-images.githubusercontent.com/40168263/188042819-fc28d453-76fd-4fe0-a611-96f1acae3f61.png)
https://www.neb.com/products/r0104-hindiii#Product%20Information
Could you help me ?

Sincerely
Johnson

**Comment by Johnsonzcode** [comment]
Is it just AAGCTT or AGCTT ?

**Comment by c-zhou** [comment]
Hi Johnson,

It should be AAGCTT.

Chenxi

**Comment by Johnsonzcode** [comment]
Thank you for your kind !
