### ISSUE TITLE
-q not work

### ISSUE THREAD

**Issue by xiekunwhy** [c-zhou/yahs#36]
Hi,

I got exactly the same results and .bin file size when using three command lines like following 

yahs v1.2a.2

yahs -e GATC --no-mem-check -o tmo tmo.pctg.fa tmo.pctg.dedup.bam
yahs -e GATC --no-mem-check -q 10 -o tmo.q10 tmo.pctg.fa tmo.pctg.dedup.bam
yahs -e GATC --no-mem-check -q 30 -o tmo.q30 tmo.pctg.fa tmo.pctg.dedup.bam

![image](https://user-images.githubusercontent.com/17738229/195000407-05877f36-aa18-4fe3-b568-a01611d6a6ea.png)

![image](https://user-images.githubusercontent.com/17738229/195000887-701e0ac7-5527-4f0f-a455-7ab52b2f7935.png)

so I think -q didn't work. Is it a bug?

Best,
Kun

**Comment by c-zhou** [comment]
Hello Kun,

For coordinate-sored and unsorted BAM inputs, the `-q` flag is suppressed. See https://github.com/c-zhou/yahs#run-yahs `NOTE 1`.

Best,
Chenxi

**Comment by xiekunwhy** [comment]
Ok, I will sort the bam first.
