### ISSUE TITLE
Haplotype-aware scaffolding for switch error correction

### ISSUE THREAD

**Issue by baozg** [c-zhou/yahs#5]
Hi, @c-zhou 

Is `yahs` do the haplotype-aware scaffolding ? Ex. the downstream of `hifiasm` HiC-phase, we get two haplotype, then cat the assembled fasta together for scaffolding. `3d-dna` did not use the haplotype information, but work well in the high heterozyogus plant genome (TrioBin [plant genome scaffolding](https://github.com/baozg/phased-assembly-check)). `AllHiC` need allele table for pruning hic links. For meidum heter genome (0.5~1%), `3d-dna` or `AllHiC` cannot scaffold the homozygous region well because the low MQ.

**Comment by c-zhou** [comment]
Hi @baozg, YaHS is not designed for haplotype-aware scaffolding. Thanks, Chenxi.

**Comment by baozg** [comment]
Thanks
