### ISSUE TITLE
 manual editing with juicer pre creating an empty bed format out_JBAT.txt file

### ISSUE THREAD

**Issue by maysonlin** [c-zhou/yahs#50]
Greeting, 
            I have followed up the manual and generated mapping .bam file by Arima Genomics' mapping pipeline. Then I used yahs, I successfully obtained the scaffold.fa file.  Followed by that, I moved to **Manual curation with Juicebox (JBAT)** step using the this command :
            `juicer pre -a -o out_JBAT all1.bed yahs.out_scaffolds_final.agp yahs.out_scaffolds_final.fa.fai >out_JBAT.log 2>&1`

However, "out_JBAT.txt " is empty, so I checked the log, which showed 

[E::make_asm_dict_from_agp] sequence ptg000045l_1 not found
[I::main_pre] make juicer pre input from BED file  all1.bed
[E::make_asm_dict_from_agp] sequence ptg000045l_1 not found
[W::make_juicer_pre_file_from_bed] sequence "ptg000001l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000016l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000002l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000113l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000021l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000131l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000063l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000008l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000073l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000015l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000092l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000010l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000009l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000045l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000038l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000085l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000043l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000019l_1" not found 
[W::make_juicer_pre_file_from_bed] sequence "ptg000023l_1" not found
.
.
.
I::make_juicer_pre_file_from_bed] 443 million records processed, 0 read pairs 
[I::make_juicer_pre_file_from_bed] 444 million records processed, 0 read pairs 
[I::make_juicer_pre_file_from_bed] 445 million records processed, 0 read pairs 
[I::make_juicer_pre_file_from_bed] 0 read pairs processed
[I::main_pre] genome size: 534549832
[I::main_pre] scale factor: 1
[I::main_pre] chromosome sizes for juicer_tools pre -
PRE_C_SIZE: assembly 534549832
[I::main_pre] JUICER_PRE CMD: java -Xmx36G -jar ${juicer_tools} pre out_JBAT.txt out_JBAT.hic <(echo "assembly 534549832")
[I::main_pre] Version: 1.1
[I::main_pre] CMD: juicer pre -a -o out_JBAT all1.bed yahs.out_scaffolds_final.agp yahs/yahs.out_scaffolds_final.fa.fai
[I::main_pre] Real time: 442.798 sec; CPU: 442.689 sec; Peak RSS: 0.001 GB

But in the input "all1.bed ", I can see "ptg000001l_1":
ptg000001l_1    9017555 9017655 A00869:687:H2JKGDSX5:1:1101:3513:1000/1 60      +
ptg000035l_1    796206  796356  A00869:687:H2JKGDSX5:1:1101:3513:1000/2 60      -

and "yahs.out_scaffolds_final.agp ":
scaffold_1      10975528        10975727        6       N       200     scaffold        yes     proximity_ligation
scaffold_1      10975728        15212573        7       W       ptg000100l_1    1       4236846 -

finally "yahs.out_scaffolds_final.fa.fai" generated by samtools, which is the only input not mentioning other contigs

scaffold_1      73057942        12      60      61
scaffold_2      70297441        74275599        60      61
scaffold_3      60369146        145744677       60      61
scaffold_4      60083703        207119988       60      61
scaffold_5      53042111        268205099       60      61
scaffold_6      52917721        322131258       60      61
scaffold_7      43201523        375930954       60      61
scaffold_8      42457413        419852515       60      61
scaffold_9      39485898        463017564       60      61
scaffold_10     23824853        503161574       60      61
scaffold_11     5153502 527383521       60      61
scaffold_12     2608000 532622928       60      61
scaffold_13     2372978 535274408       60      61
scaffold_14     1364889 537686949       60      61
scaffold_15     882000  539074600       60      61
scaffold_16     854628  539971313       60      61
scaffold_17     629000  540840198       60      61
scaffold_18     460000  541479695       60      61
scaffold_19     419854  541947375       60      61
scaffold_20     207000  542374240       60      61
scaffold_21     154887  542584703       60      61
scaffold_22     139000  542742185       60      61
scaffold_23     100000  542883515       60      61

I have tried using original mapping .bam as input, .bin file from yahs output , none of them worked, they all showed "[W::make_juicer_pre_file_from_bed] sequence "ptg000001l_1" not found ", please let me know if there is anything I can do to fix this issue. Thank you for your time!

**Comment by c-zhou** [comment]
Hello @maysonlin,

In the command `juicer pre -a -o out_JBAT all1.bed yahs.out_scaffolds_final.agp yahs.out_scaffolds_final.fa.fai >out_JBAT.log 2>&1`, the `yahs.out_scaffolds_final.fa.fai` file should be replaced with the FASTA index file for your contigs (used for scaffolding).

Best,
Chenxi

**Comment by maysonlin** [comment]
Sorry for the late reply, but that really fixed the issue, thank you!
