### ISSUE TITLE
Scaling issues for large genomes on juicebox

### ISSUE THREAD

**Issue by sheinasim** [c-zhou/yahs#51]
Hello there!

I'm using juicebox to edit my hic assemblies, and I've noticed that for larger genomes (larger than 2 gb), the .hic file contacts and the .assembly file contig boundaries to not align. Is there a way to get them to match up? How could I scale my .assembly file?

I'm using the following commands to create the .hic and .assembly file:

```
juicer_pre -a -o out_ec yahsout_ec.bin yahsout_ec_scaffolds_final.agp contig.fai 2>ec_juicer_pre.log

genomesize=`cat ec_juicer_pre.log | grep "PRE_C_SIZE" | tr " " "\n" | tail -n 1`

java -Xmx155G -jar juicer_tools_1.22.01.jar pre out_ec.txt out_ec.hic <(echo "assembly ${genomesize}")
```

Thank you!
Sheina

**Comment by c-zhou** [comment]
Hello Sheina,

You need to set the scale factor in Juicebox following the instructions in `NOTE 3` on the GitHub main page.

Best,
Chenxi

**Comment by sheinasim** [comment]
Hello Chenxi,

Thank you so much for your reply. 

This is perfect.

Best wishes,
Sheina

**Comment by wjq1981** [comment]
> Hello, where is this 'NOTE3'? I didn't find it, can you tell me?

**Comment by mcshane** [comment]
https://github.com/c-zhou/yahs/blob/0f81dbf678abd86b601374f960bcb4e0b8d33426/README.md?plain=1#L85

**Comment by wjq1981** [comment]
> 

Thank you very much！
