### ISSUE TITLE
segmentation fault when scaffolding a plant genome

### ISSUE THREAD

**Issue by baozg** [c-zhou/yahs#6]
Hi, @c-zhou 

I run the latest `yahs` from the github issue to scaffolding a 4.5G genome, but it end with the segementation fault. Here is the command I use 

```bash
# convert the merge_nodup of juicer output to bed
utg000001l      68215   68365   A00301:339:HV7YCDSX2:3:2602:6045:36166/1        60      +
utg000001l      68754   68904   A00301:339:HV7YCDSX2:3:2602:6045:36166/2        32      -
utg000001l      68241   68391   A00234:846:HTWKCDSX2:1:1122:23809:13385/1       55      +
utg000001l      68760   68910   A00234:846:HTWKCDSX2:1:1122:23809:13385/2       32      -
utg000001l      68243   68393   A00234:846:HTWKCDSX2:1:1447:24704:2033/1        59      +
utg000001l      68759   68909   A00234:846:HTWKCDSX2:1:1447:24704:2033/2        32      -
utg000001l      68251   68401   A00234:846:HTWKCDSX2:1:1671:23637:36699/1       60      +
utg000001l      68775   68925   A00234:846:HTWKCDSX2:1:1671:23637:36699/2       34      -
utg000001l      68266   68416   A00301:340:HTWMWDSX2:3:2511:21052:6136/1        60      +

# yahs
/data/software/yahs/yahs --no-contig-ec -o yahs_Q30 contigs.fa yahs_Q30.bed

# log

[I::print_asm_stats] assembly stats:
[I::print_asm_stats] N50: 1556949 (n = 730)
[I::print_asm_stats] N90: 52585 (n = 5902)
[I::run_yahs] scaffolding round 1 resolution = 10000
[1]    48532 segmentation fault  /data/software/yahs/yahs/yahs --no-contig-ec -o yahs_Q30 contigs.fa

```

**Comment by c-zhou** [comment]
Hi @baozg,

Thanks for using YaHS. Unfortunately, there is no enough information in the log for me to locate the problem. I can see the BED file is fine as the data preprocessing was successfully done. It looks to me there was no sufficient memory for a 10Kb resolution. How much memory have you assigned?

YaHS has a module to check memory consumption and is supposed to skip high resolutions if memory is not sufficient. It was, somehow, not working in your system I guess. I tried to improve this module and has checked in to the repo. You might give it a go. I also added more log information which should help to locate the segfault. If the problem persists, please let me know.

Best,
Chenxi

**Comment by c-zhou** [comment]
To quickly check if it is a memory problem, you could try to start with a higher resolution. For example, with `-r 50000,100000,200000,500000,1000000,2000000,5000000,10000000,20000000,50000000,100000000` it will start with a 50Kb resolution. However, with a 50Kb resolution, all contigs <100Kb (2*50Kb) will be ignored. Your assembly seems to have a whole bunch of such contigs as the N90 is ~52Kb. It might be fine, as these short contigs are difficult to scaffold anyway and will lead to potential scaffolding errors.

Best,
Chenxi

**Comment by baozg** [comment]
The node have 256G RAM. `yahs` use the 50G memory max (look by top). When I try `-r 100000,200000,500000,1000000,2000000,5000000,10000000,20000000,50000000,100000000`, it also have segement fault. I do use a very fragment genome since it from the hifiasm utg.

```bash
[I::dump_links_from_bed_file] 151 million records processed, 75500000 read pairs
[I::dump_links_from_bed_file] dumped 75642522 read pairs: 36101437 intra links + 39541085 inter links
[2]    60385 segmentation fault  /data/software/yahs/yahs -r  -o yahs_Q30 contigs.fa M32_MQ30.bed
```

**Comment by baozg** [comment]
I try the latest yahs from github, the `yahs` log :
```bash
[I::dump_links_from_bed_file] 151 million records processed, 75500000 read pairs
[I::dump_links_from_bed_file] dumped 75642522 read pairs: 36101437 intra links + 39541085 inter links
[I::run_yahs] RAM total: 251.740GB
[I::run_yahs] RAM limit: 28.395GB
[1]    31896 segmentation fault  /data/software/yahs/20211223/yahs -q 30 contigs.fa M32_MQ30.bed > yahs.log
```

Afer 3d-dna ~1000 iteration with (-q 30) , the scaffolding run successfully

**Comment by c-zhou** [comment]
Hello @baozg,

Sorry for the late reply. I am just back from holiday.

I cannot really tell where the problem was raised solely based on the information you provided here. I still suspect it is a memory issue. The log file says there is 251Gb memory on your system but the maximum that YaHS can use is ~28Gb. If you did see 50G memory usage, there might be something wrong.

Best,
Chenxi

**Comment by baozg** [comment]
Does the bed have any order assmumption (sort by readnum default) ? `SALSA2` can run the pipeline successfully without any error in a 96G RAM node. What's the typical RAM usage for `yahs`?

**Comment by c-zhou** [comment]
YaHS can take exactly the same BED input as SALSA2.

It is hard to tell the memory consumption solely based on the genome size. It really matters the length distribution of the contigs. The log will tell you some information about memory usage. I believe it will automatically skip high-resolution scaffolding round if the memory is insufficient. Not sure if you have seen any.

Chenxi
