### ISSUE TITLE
yahs can't read PA5 file format file

### ISSUE THREAD

**Issue by socialhang** [c-zhou/yahs#69]
Hi, @richarddurbin @c-zhou 

This is my command:
`yahs hifiasm.asm.p_utg.fa all_links.nS.pa5`

This is my error:
`[E::main] unknown link file format. File extension .bam, .bed or .bin is expected`

Does yahs software not support pa5 format anymore?

Looking forward to your reply！

best wishes！

**Comment by le1016** [comment]
I had the same problem, how did you solve it @socialhang
