### ISSUE TITLE
Using Yahs only to break contigs

### ISSUE THREAD

**Issue by haigdjambazian** [c-zhou/yahs#74]
Is there an option to run Yahs as a contig correction tool only?

After the initial assembly I want to first be able to break the contigs where needed before removing duplicates and running yahs for scaffolding.

Do you think I can take the final yahs output and break it on the N's and get back the original contigs broken on the missassemblies where yahs did a correction?

Thank you.

**Comment by c-zhou** [comment]
Hello @haigdjambazian,

The intermediate AGP files named `*_inital_break_*.agp` contain information for contig corrections. The numbers in the file names indicate the error correction round - you can use the one generated in the last round. To get the FASTA file, you can use the `agp_to_fasta` tool coming with yahs.

Chenxi

**Comment by haigdjambazian** [comment]
This worked perfectly. Thanks! We can see the slight differences between the assemblies pre/post contig correction:
<img width="984" alt="Screen Shot 2023-11-07 at 7 43 23 PM" src="https://github.com/c-zhou/yahs/assets/6486013/539b1051-513b-46d9-b041-72abaee16869">
Thanks again for the tip!
