### ISSUE TITLE
How to cite yahs?

### ISSUE THREAD

**Issue by sheinasim** [c-zhou/yahs#8]
Hello there!

This software is amazing and is perfect for the hic scaffolding that I do.

Is there a publication I can cite or perhaps a doi?

Best wishes,
Sheina

**Comment by c-zhou** [comment]
Hi Sheina,

Thanks for using YaHS. We have a manuscript in preparation. A preprint should come out soon. I also added a Zenodo DOI if you prefer.

Best,
Chenxi
