### ISSUE TITLE
No intra links and inter links dumped from bam file 

### ISSUE THREAD

**Issue by shiyi-pan** [c-zhou/yahs#89]
Hi, I want to use yahs  to scaffolding my genome. I aligned HiC reads with chromap and scaffolded with yahs. Here is my scripts:

samtools faidx hifiasm.fa
chromap -i -r hifiasm.fa -o hifiasm.fa.index
chromap --preset hic -r hifiasm.fa -x hifiasm.fa.index -1 HiC_1.fq.gz -2 HiC_2.fq.gz --remove-pcr-duplicates --SAM -o aligned.sam -t 4
samtools view -bh aligned.sam | samtools sort -@ 4 -n > aligned.bam
yahs NN1138_hifiasm.fa aligned.bam

The size of aligned.bam is 39G. But there are no links  dumped from the bam file . Here is part of logs:

[I::dump_links_from_bam_file] 299 million records processed, 0 read pairs
[I::dump_links_from_bam_file] 300 million records processed, 0 read pairs
[I::dump_links_from_bam_file] 301 million records processed, 0 read pairs
[I::dump_links_from_bam_file] 302 million records processed, 0 read pairs
[I::dump_links_from_bam_file] 303 million records processed, 0 read pairs
[I::dump_links_from_bam_file] 304 million records processed, 0 read pairs
[I::dump_links_from_bam_file] 305 million records processed, 0 read pairs
[I::dump_links_from_bam_file] 306 million records processed, 0 read pairs
[I::dump_links_from_bam_file] 307 million records processed, 0 read pairs
[I::dump_links_from_bam_file] 308 million records processed, 0 read pairs
[I::dump_links_from_bam_file] 309 million records processed, 0 read pairs
[I::dump_links_from_bam_file] dumped 0 read pairs from 309210925 records: 0 intra links + 0 inter links

Could you give me some advices to solve this problem.
Thank you very much.

**Comment by shiyi-pan** [comment]
Thank you, Chenxi. The problem is solved.

**Comment by c-zhou** [comment]
No problem. I will close the issue. Chenxi
