### ISSUE TITLE
Creating contig sorted pretext file?

### ISSUE THREAD

**Issue by sheinasim** [c-zhou/yahs#9]
Hello Chenxi!

Thank you again for creating this wonderful program!

I'm trying to create a contig sorted Pretext file to input into PretextView, but I am struggling to create the file properly using the recommended commands.

Is it possible to create the pretext files that are analogous to the JBAT assembly mode files? I'm looking to order the contigs the way that yahs does, and then make necessary changes using PretextView. I have successfully produced the Pretext files using the commands at the end of run_yahs.sh, but the scaffolds don't show the contig boundaries.

I tried:

`juicer_pre -a -o genome_ec genome_yahsout_ec.bin genome_yahsout_ec_scaffolds_final.agp genome.fai 2>ec_juicer_pre.log`

`cut -f1-2 genome.fai >genome_yahsout_ec_scaffolds_final.chrom.sizes`

`(awk 'BEGIN{print "## pairs format v1.0"} {print "#chromsize:\t"$1"\t"$2} END {print "#columns:\treadID\tchr1\tpos1\tchr2\tpos2\tstrand1\tstrand2"}' genome_yahsout_ec_scaffolds_final.chrom.sizes; awk '{print ".\t"$2"\t"$3"\t"$6"\t"$7"\t.\t."}' genome_ec.txt) | PretextMap -o genome.yahs.mapq10.pretext --mapq 10`

It produces a Pretext file, but it doesn't have any contacts in it.

Thanks!
Sheina

**Comment by c-zhou** [comment]
Hi Sheina,

Sorry for the late reply.

I am not quite sure what is the problem. The pretextmap generated with the command you posted should be fine for pretextview. May I ask what operating system are you using for pretextview? Also, can you try to generate a Snapshot for the pretextmap and see if there are any hic signals? The command is something like `PretextSnapshot -m genome.yahs.mapq10.pretext --sequences "=full" -o ${outdir}`. Please check the demo script run_yahs.sh for details.

Best,
Chenxi

**Comment by baozg** [comment]
Hi, Chenxi

Is it possible due to the inconsistent between the `chrom.size` and `genome_ec.txt`? The chrom size was from scaffold, but the pairs txt only have assembly-mode. 

So how to use pretextmap assembly mode with yahs mode? The demo only include the JBAT mode. For large genome, juicerbox is pretty slow.

Thanks
Zhigui

**Comment by c-zhou** [comment]
Hi @baozg and @sheinasim ,

I think you are right @baozg. The chromosome size file (`genome_yahsout_ec_scaffolds_final.chrom.sizes`) @sheinasim used for PretextMap was not right. From my understanding, the `genome.fai` file was for the input contig file. PretextMap, however, expects to see a chromosome size file for the scaffolds. 

@baozg, what @sheinasim did should work. There are more details in the example script file `run_yahs.sh` (line 42-46) if you want to check. 

Best,
Chenxi
