### ISSUE TITLE
specifying restriction enzyme cutting sites with -e

### ISSUE THREAD

**Issue by leleory** [c-zhou/yahs#93]
Hi Chenxi,

Generally, I wonder how important it is to specify restriction enzyme cutting sites and also what happens if these are not specified. 

Also, can you please give me an example of how can I specify multiple RE cutting sites? Can ambiguity characters be used to specify multiple REs?

So, for example, if I have the following RE motifs from Arima: ^GATC and G^ANTC, then can I specify these as: 
-e GATC,GANTC

Thank you,
Lel

**Comment by c-zhou** [comment]
Hi Lel,

From our experience, it does not make much difference whether to specify restriction enzymes or not.

```
So, for example, if I have the following RE motifs from Arima: ^GATC and G^ANTC, then can I specify these as:
-e GATC,GANTC
```
Yes, this would work.

Best,
Chenxi

**Comment by leleory** [comment]
That is great, thank you for the info!
Best wishes,
Lel
